POST http://localhost:3000/api/
Content-Type: application/json

{
  "titi": "Nejma"
}

###
POST http://localhost:3000/api/ordinateur/cartemere/
Content-Type: application/json

{
  "name": "Carte mère test"
}

###
POST http://localhost:3000/api/ordinateur/ram/
Content-Type: application/json

{
  "name": "Ram test"
}

###
POST http://localhost:3000/api/ordinateur/processeur/
Content-Type: application/json

{
  "name": "Processeur test"
}

###
POST http://localhost:3000/api/ordinateur/
Content-Type: application/json

{
  "name": "Ordinateur test",
  "ramId": 1,
  "cartemereId": 1,
  "processeurId": 1
}

###
DELETE http://localhost:3000/api/ordinateur/cartemere/1

###
PUT http://localhost:3000/api/ordinateur/cartemere/1

###
GET http://localhost:3000/api/ordinateur